version: '2'
services:
  traefik:
    image: traefik
    command: --web --docker --docker.domain=${LOCAL_DOMAIN} --logLevel=DEBUG
    ports:
      - "88:80"
      - "8888:8888"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/null:/traefik.toml


  fyrvall-mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    expose:
      - "3306"
    ports:
      - "3306:3306"
  
  fyrvall-site:
    build: ../sites/Fyrvall
    depends_on:
     - fyrvall-mysql
    expose:
      - "80"
    labels:
      - traefik.frontend.rule=Host:${LOCAL_DOMAIN}

  auth-mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    expose:
      - "3306"
    ports:
      - "3307:3306"

  auth-site:
    build: ../sites/Auth
    depends_on:
      - auth-mysql
    expose:
      - "80"
    labels:
      - traefik.frontend.rule=Host:auth.${LOCAL_DOMAIN}

  manage-mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    expose:
      - "3306"
    ports:
      - "3308:3306"

  manage-site:
    build: ../sites/Manage
    depends_on:
      - manage-mysql
    expose:
      - "80"
    labels:
      - traefik.frontend.rule=Host:manage.${LOCAL_DOMAIN}

  documentation-mysql:
    image: mysql
    environment: 
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    expose:
      - "3306"
    ports:
      - "3309:3306"

  documentation-site:
    build: ../sites/Documentation
    depends_on:
      - documentation-mysql
    expose:
      - "80"
    labels:
      - traefik.frontend.rule=Host:documentation.${LOCAL_DOMAIN}

  share-mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    expose:
      - "3306"
    ports:
      - "3310:3306"
#    volumes:
#      - share-mysql-data:/var/lib/mysql

  share-site:
    build: ../sites/Share
    depends_on:
      - share-mysql
    expose: 
      - "80"
    labels:
      - traefik.frontend.rule=Host:share.${LOCAL_DOMAIN}
    volumes:
      - share-site-uploads:/var/uploads

  unity-packer:
    build: ../sites/unity-packer
    depends_on:
      - traefik
    expose:
      - "80"
    labels:
      - traefik.frontend.rule=Host:unitypacker.${LOCAL_DOMAIN}
      
  webhook-forwarder-mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: webhook
    expose:
      - "3306"
    ports:
      - "3311:3306"
      
  webhook-forwarder-site:
    build: ../sites/WebhookForwarder
    depends_on:
      - webhook-forwarder-mysql
      - traefik
    expose:
      - "80"
    labels:
      - traefik.frontend.rule=Host:webhookforwarder.${LOCAL_DOMAIN}
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      
volumes:
  fyrvall-mysql-data:
  auth-mysql-data:
  manage-mysql-data:
  documentation-mysql-data:
  share-mysql-data:
  share-site-uploads: