version: '2'
services:
  traefik:
    image: traefik
    command: --web --docker --docker.domain=${LOCAL_DOMAIN} --logLevel=DEBUG
    ports:
      - "443:443"
      - "${LOCAL_PORT}:80"
      - "8888:8888"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/null:/traefik.toml
#      - ./traefik.toml:/traefik.toml
#      - ./fyrvall.json:/fyrvall.json


  fyrvall-mysql:
    container_name: fyrvall-mysql
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: fyrvall
    expose:
      - "3306"
    ports:
      - "3306:3306"
    volumes:
      - fyrvall-mysql-data:/var/lib/mysql
  
  fyrvall-site:
    container_name: fyrvall-site
    build: ../sites/Fyrvall
    depends_on:
     - fyrvall-mysql
    expose:
      - "80"
    labels:
      - traefik.frontend.rule=Host:${LOCAL_DOMAIN}

  auth-mysql:
    container_name: auth-mysql
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: auth
    expose:
      - "3306"
    ports:
      - "3307:3306"
    volumes:
      - auth-mysql-data:/var/lib/mysql

  auth-site:
    container_name: auth-site
    build: ../sites/Auth
    depends_on:
      - traefik
      - auth-mysql
    expose:
      - "80"
    labels:
      - traefik.frontend.rule=Host:auth.${LOCAL_DOMAIN}
    environment:
      PRE_SHARED_KEY: ${PRE_SHARED_KEY}
     

  manage-mysql:
    container_name: manage-mysql
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: manage
    expose:
      - "3306"
    ports:
      - "3308:3306"
    volumes:
      - manage-mysql-data:/var/lib/mysql
    

  manage-site:
    container_name: manage-site
    build: ../sites/Manage
    depends_on:
      - manage-mysql
      - traefik
    expose:
      - "80"
    labels:
      - traefik.frontend.rule=Host:manage.${LOCAL_DOMAIN}

  documentation-mysql:
    container_name: documentation-mysql
    image: mysql
    environment: 
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: documentation
    expose:
      - "3306"
    ports:
      - "3309:3306"
    volumes:
      - documentation-mysql-data:/var/lib/mysql

  documentation-site:
    container_name: documentation-site
    build: ../sites/Documentation
    depends_on:
      - documentation-mysql
    expose:
      - "80"
    labels:
      - traefik.frontend.rule=Host:documentation.${LOCAL_DOMAIN}

  share-mysql:
    container_name: share-mysql
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: share
    expose:
      - "3306"
    ports: 
      - "3310:3306"
    volumes:
      - share-mysql-data:/var/lib/mysql

  share-site:
    container_name: share-site
    build: ../sites/Share
    depends_on:
      - share-mysql
    expose: 
      - "80"
    labels:
      - traefik.frontend.rule=Host:share.${LOCAL_DOMAIN}
    volumes:
      - share-site-uploads:/var/www/html/uploads

  unity-packer:
    container_name: unity-packer
    build: ../sites/unity-packer
    depends_on:
      - traefik
    expose:
      - "80"
    labels:
      - traefik.frontend.rule=Host:unitypacker.${LOCAL_DOMAIN}
      
  webhook-forwarder-mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: webhook
      MYSQL_AIO: 0
    expose:
      - "3306"
    ports:
      - "3311:3306"
      
  webhook-forwarder-site:
    build: ../sites/WebhookForwarder
    depends_on:
      - webhook-forwarder-mysql
      - traefik
    expose:
      - "80"
    labels:
      - traefik.frontend.rule=Host:webhookforwarder.${LOCAL_DOMAIN}
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      
volumes:
  fyrvall-mysql-data:
  auth-mysql-data:
  manage-mysql-data:
  documentation-mysql-data:
  share-mysql-data:
  share-site-uploads:
